#!/usr/bin/env php
<?php
if ($argc == 2) {
    $number = $argv[1];
} else {
    info("Input number:");
    $number = trim(fgets(STDIN));
}

$results = unpack("C*", pack("L",$number));
// print_r($results);

foreach($results as $result){
 echo str_pad(dechex($result),2,'0',STR_PAD_LEFT).'       ';
}

echo PHP_EOL;

foreach($results as $result){
 echo str_pad(decbin($result),8,'0',STR_PAD_LEFT).' ';
}

echo PHP_EOL;
// echo bin2hex(pack("L",12345));
