#!/usr/bin/env php
<?php
if ($argc == 2) {
    $number = $argv[1];
} else {
    info("Input number:");
    $number = trim(fgets(STDIN));
}

$results = unpack("C*", pack("L",$number));
// print_r($results);

foreach($results as $result){
 echo dechex($result).'       ';
}

echo PHP_EOL;

foreach($results as $result){
 echo decbin($result).' ';
}

echo PHP_EOL;
// echo bin2hex(pack("L",12345));
